language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: p.krautzberger@gmail.com
  api_key:
    secure: hhSQmz/nvRYzC446LEpwFnelTSteGjjgbS4nQMDRSsNbIUU7lzq060qz9CbV9wl7W8XA2q7IeXdcH/nPDpbCvRtoaKYag+UzaP5QkJnuqeD9fyg0nPQlgYxiwmTttJTCDcV9NRvZPMi8aV6b5+VE6FM/7Bcfgmp/iy23g/WfqwEeG+N1Sa7R8mONWa4fTfWQyViIIVdaM2X3bwMtdV2o0sYGg2eadFtkAw3awB7oZvVvABxrqTTUwVKSvHNaRWBPLL45VRI7/14DKJOEWBuT6GZ7xaaBs/NC38IMOzZ4D7IN7+FA+3rbFHZaTfCWrxU3Qy1GB2KFjGIpw5ujXmpg7YRBpmJPXBEoMawCBhzDWGz+qAwIzFB4FNUHleViWU2QR22maRe4TNbzN9HKzLXio8qxq+Vl2JmIAL/oE1JWW3u4Eng5ix6IEGcIYp1IaxzUWO30acqeFwUGlKN3V0rDs4iQJrpKtMONYslhp7r14SISZXVqJ0IePIeYu/5Eu0Z422XyMiUUayrsEyWR9ciujPhaUrA95YlZzXyJ4NVE8kPQLeYRAs+koOwXRppYZkwOewWqRA93XoUWNIknorTqOxQlBgpyyu4baiWuyPEe3GW8N3QJLaxysGkYKOAc9VrOvZbyVkllYLoLidH+4U9w0/A2N7gWdVILcizf/zubf1s=
  on:
    tags: true
    repo: pkra/mathjax-node-sre
